/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Test4RouteImport } from './routes/test4'
import { Route as Test3RouteImport } from './routes/test3'
import { Route as Test2RouteImport } from './routes/test2'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'

const Test4Route = Test4RouteImport.update({
  id: '/test4',
  path: '/test4',
  getParentRoute: () => rootRouteImport,
} as any)
const Test3Route = Test3RouteImport.update({
  id: '/test3',
  path: '/test3',
  getParentRoute: () => rootRouteImport,
} as any)
const Test2Route = Test2RouteImport.update({
  id: '/test2',
  path: '/test2',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/test2': typeof Test2Route
  '/test3': typeof Test3Route
  '/test4': typeof Test4Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test' | '/test2' | '/test3' | '/test4'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test' | '/test2' | '/test3' | '/test4'
  id: '__root__' | '/' | '/test' | '/test2' | '/test3' | '/test4'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  Test2Route: typeof Test2Route
  Test3Route: typeof Test3Route
  Test4Route: typeof Test4Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test4': {
      id: '/test4'
      path: '/test4'
      fullPath: '/test4'
      preLoaderRoute: typeof Test4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test3': {
      id: '/test3'
      path: '/test3'
      fullPath: '/test3'
      preLoaderRoute: typeof Test3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test2': {
      id: '/test2'
      path: '/test2'
      fullPath: '/test2'
      preLoaderRoute: typeof Test2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  Test2Route: Test2Route,
  Test3Route: Test3Route,
  Test4Route: Test4Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
