name: aurora-demo

services:
  postgres:
    image: postgres
    container_name: aurora-demo-postgres
    environment:
      POSTGRES_DB: aurora-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5900:5432"
    volumes:
      - aurora-demo_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  aurora-demo_postgres_data:
